### ISSUE TITLE
unable to find templates

### ISSUE THREAD

**Issue by nostalgicdodo** [numtel/meteor-publicsources#2]
I followed the example you provided closely but iron:router says "couldn't find template "hello" or "Hello". The css files are loaded though.
If I pull the templates out of the public folder and change the references in `publicsources.json` accordingly, then it works, but that defeats the purpose.

any idea what might be causing this?

**Comment by numtel** [comment]
I cannot tell you without seeing your code. Please post a link to a repo that reproduces this with the minimum code.

**Comment by nostalgicdodo** [comment]
sure. it's up [here](https://github.com/nostalgicdodo/lazy). i've used jade in this case but I get the same complaint with spacebars as well.
hope it is not too much code to go through.

**Comment by numtel** [comment]
You need to include the javascript files in the preloader config as well as the CSS files.

``` javascript

Router.route("/", {

    name: "home",
    template: "first",

    controller: PreloadController,
    preload: {
        sync: "first.js", // <--------- This line was missing
        styles: "first.css"
    }

});
```

**Comment by nostalgicdodo** [comment]
woah, ok. that was strange. I didn't have any JS for the template so I didn't think to add that line.
thanks a ton!
