### ISSUE TITLE
Programmatic example?

### ISSUE THREAD

**Issue by trusktr** [numtel/meteor-publicsources#4]
Can you show a programmatic example without using iron router? I'm using [flow-router](https://github.com/meteorhacks/flow-router). What might I be able to do in the `action` function that handles a route?

**Comment by numtel** [comment]
I don't know, I've never used flow-router. It should be fairly simple to adapt to any system. Just load the JS and/or CSS files when you are ready for them. I probably won't investigate this immediately but may look into it eventually.
