### ISSUE TITLE
Regex for files in  .publicsources.json.

### ISSUE THREAD

**Issue by virgotopia** [numtel/meteor-publicsources#6]
Hello, thx for this package.
It would be nice to allow some kind of regex/glob for files in custom.publicsources.json.

Instead of
 {
  "admin": [ 
    "admin/templates.html",
    /*\* ...some other 24 files... */
    "admin/styles.less",
    "admin/main.coffee"
  ]
}

to have something like:
{
  "admin": [ 
    "admin/*"
 ]
}

so that all files inside this folder will be included.

What do you think ?

**Comment by numtel** [comment]
That would be a good feature. If you provide a pull request I will review it and release a new version.

**Comment by virgotopia** [comment]
Cool, I'm working on it

**Comment by numtel** [comment]
@virgotopia Any luck on this?

**Comment by numtel** [comment]
This package is now deprecated. This feature has been included in the new [`numtel:lazy-bundles` package](https://github.com/numtel/meteor-lazy-bundles).
